services:
  auth-service:
    image: tobiasbrandy/auth-service:latest
    restart: unless-stopped
    expose:
      - "80"
    environment:
      APP__ENV: ${APP__ENV:-dev}
      APP__AUTH__JWT_SECRETS: ${APP__AUTH__JWT_SECRETS:-'{}'}

  app-service:
    image: tobiasbrandy/app-service:latest
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - auth-service

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/cert:/etc/ssl/cert:ro
    depends_on:
      - auth-service
      - app-service