services:
  auth-service:
    image: tobiasbrandy/auth-service:latest
    restart: always
    ports:
      - "3000:3000"

  app-service:
    image: tobiasbrandy/app-service:latest
    restart: always
    environment:
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP:-localhost}
    ports:
      - "8000:8000"
    depends_on:
      - auth-service