services:
  auth-service:
    build:
      context: .
      target: auth-service
    ports:
      - "3000:80"

  app-service:
    build:
      context: .
      target: app-service  
    ports:
      - "8000:80"

  nginx:
    ports:
      - "8080:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro

  pg:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "rust_auth_db"
      POSTGRES_PASSWORD: "postgres"
