services:
  auth-service:
    image: tobiasbrandy/auth-service:latest
    restart: always
    expose:
      - "3000"
    environment:
      APP__ENV: ${APP__ENV:-dev}
      APP__HOST: ${APP__HOST:-localhost}
      APP__AUTH__JWT_SECRETS: ${APP__AUTH__JWT_SECRETS:-'{}'}

  app-service:
    image: tobiasbrandy/app-service:latest
    restart: always
    expose:
      - "8000"
    depends_on:
      - auth-service
    environment:
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP:-localhost}

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - app-service