# CI/CD test environment

[db]
user = "postgres"
database = "postgres"
password = "postgres"
port = 5433
max_connections = 1000

[redis]
port = 6380
password = "redis"

[auth]
jwt_secrets = { "1111111111" = "test-secret" }
